version: '3.1'

services:
  server:
    build:
      context: .
      dockerfile: server/docker/Dockerfile
    container_name: ${CONTAINER_NAME}-server
    depends_on:
      - db
    ports:
      - ${APACHE_PORT}:80
    volumes:
      - ./src:/var/www/html
      - ./logs/apache2:/var/log/apache2

  db:
    image: mysql:5.5
    restart: always
    container_name: ${CONTAINER_NAME}-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - /var/lib/mysql/${MYSQL_DATABASE}:/var/lib/mysql/${MYSQL_DATABASE}
