version: '3.1'

services:
  # furkid-client:
  #   build: 
  #     context: .
  #     dockerfile: client/Dockerfile
  #   container_name: ${CONTAINER_NAME}-client
  #   ports:
  #     - ${VUE_PORT}:8080
  #   tty: true

  furkid-server:
    build:
      context: .
      dockerfile: server/docker/Dockerfile
    container_name: ${CONTAINER_NAME}-server
    depends_on:
      # - furkid-client
      - furkid-db
    ports:
      - ${APACHE_PORT}:80
    volumes:
      - ./client/dist:/var/www/html/furkid
      - ./server/src:/var/www/html
      - ./logs/apache2:/var/log/apache2

  furkid-db:
    image: mysql:5.5
    restart: always
    container_name: ${CONTAINER_NAME}-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
